# Generated by Django 2.2.6 on 2019-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20191109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='diabetic',
            field=models.BooleanField(verbose_name='Diabetic'),
        ),
    ]
