# Generated by Django 2.2.6 on 2019-11-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20191109_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
