# Generated by Django 2.2.6 on 2019-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20191109_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine',
            field=models.CharField(blank=True, choices=[('rabies', 'Rabies'), ('Bordtella', 'Bordtella'), ('Canine Distemper / Parvo Combo', 'Canine Distemper / Parvo Combo'), ('Canine Influenza', 'Canine Influenza'), ('Leptospirosis (Lepto4)', 'Leptospirosis (Lepto4)'), ('Canine C3', 'Canine C3'), ('Canine C4', 'Canine C4'), ('Canine C5', 'Canine C5'), ('Canine C7', 'Canine C7'), ('Feline FVRCP group (rhino, calic, distemper)', 'Feline FVRCP group (rhino, calic, distemper)'), ('Feline Herpesvirus (FHV)', 'Feline Herpesvirus (FHV)'), ('Feline Calicivirus (FCV)', 'Feline Calicivirus (FCV)'), ('Feline Panleukopenia (FPK)', 'Feline Panleukopenia (FPK)')], max_length=40),
        ),
    ]
