# Generated by Django 2.2.6 on 2019-11-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20191110_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
